### ISSUE TITLE
Makerbase

### ISSUE THREAD

**Issue by ahdinosaur** [hannobraun/cnc-mill#2]
you might be interested: https://makerbase.aliexpress.com/store/1047297

**Comment by hannobraun** [comment]
That link is only showing a blank page for me. Maybe it's a temporary error, I'll have a look later. Thanks!

**Comment by hannobraun** [comment]
The link still won't work for me, but this one does: https://www.aliexpress.com/store/1047297

Looks like the controller boards are all focused on either 3D printers or servo motors, but they have some really interesting stepper driver boards!

**Comment by ahdinosaur** [comment]
yeah as with any direct-from-China supplier it can be difficult to grok the product descriptions and documentation, but at the same time is usually much more bang for buck.

from [the "Hardware that runs FluidNC" page](https://github.com/bdring/FluidNC/wiki/Hardware-that-Runs-FluidNC), seems the Makerbase products that work with FluidNC are:

- [Makerbase MKS DLC32](https://www.aliexpress.com/item/1005003183498253.html) ([GitHub repo](https://github.com/makerbase-mks/MKS-DLC32))
- [Makerbase MKS Tinybee](https://www.aliexpress.com/item/1005003639545394.html) ([GitHub repo](https://github.com/makerbase-mks/MKS-TinyBee))

**Comment by hannobraun** [comment]
I swear I looked at all boards in the Makerbase store, but I missed the DLC32. All the others I saw (including the Tinybee) seem to be targeted at 3D printers.

I mean, maybe it doesn't matter in the end, and that "heat bed" output is just some PWM that can be used to control a spindle just as easily. I don't know. Still digging through it all, trying to understand :smile:
