### ISSUE TITLE
BulkMan3D

### ISSUE THREAD

**Issue by ahdinosaur** [hannobraun/cnc-mill#3]
you may be interested: https://bulkman3d.com/ ( https://www.aliexpress.com/store/1752067 )

based on https://openbuilds.com/, i believe is the source of similar maker stores

**Comment by hannobraun** [comment]
Thank you! I've only started looking at shops where I can buy parts, so this is very helpful. That link to OpenBuilds is also gold. I was vaguely aware of it, but hadn't thought about it recently.

**Comment by ahdinosaur** [comment]
as another example, since you mentioned wanting a gantry-based design, might be worth looking at the latest machine from BulkMan3D, the Ultimate Bee: https://bulkman3d.com/knowledge-base/ultimate-bee/ :bee: 

is the latest "OpenBuilds" -style design, but with the latest "best practices" for rigidity: c-beam linear extrusions, linear rails > vslot wheels, ball screws > acme screws.

might be out of your price range though: [bulkman3d.com store](https://bulkman3d.com/product/ultimate-bee-cnc-router-machine-full-kit-ball-screw-quiet-transmission/) | [AliExpress store](https://www.aliexpress.com/store/group/ULTIMATE-Bee-CNC/1752067_40000000306152.html). for me that's mostly because shipping is expensive, maybe [this](https://www.aliexpress.com/item/1005004128570239.html) plus locally sourced components is under budget.

**Comment by hannobraun** [comment]
Thanks! More things to look at :smile:
