### ISSUE TITLE
Mostly Printed CNC

### ISSUE THREAD

**Issue by ahdinosaur** [hannobraun/cnc-mill#4]
was looking at [Marlin](https://marlinfw.org/) CNC machines, then stumbled on this: [Mostly Printed CNC](https://docs.v1engineering.com/mpcnc/intro/) :purple_heart:

**Comment by hannobraun** [comment]
Oh, I didn't know people used Marlin for non-printers! I knew about Mostly Printed CNC, but never really looked into it. Interesting design!

I've yet to really look into existing designs. I wanted to do more research first, so I have a better idea of what I'm looking for.

**Comment by ahdinosaur** [comment]
by the way, i found another design with a similar theme: [PrintNC](https://wiki.printnc.info/en/home)

**Comment by hannobraun** [comment]
Thanks, that one looks interesting! Much more traditional design than the other one. Will add it to the notes.
